// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://wisprflow.com/
// Generated: 2026-07-06T16:39:09.610Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#1a1a1a' | '#ffffeb' | '#000000' | '#f0d7ff' | '#8a8a80' | '#ffffff' | '#e4e4d0' | '#333333' | '#034f46' | '#ffa946';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Figtree' | 'Eb garamond';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '600' | '700' | '500';

export type SpacingToken = '2px' | '32px' | '48px' | '59px' | '64px' | '70px' | '80px' | '93px' | '104px' | '112px' | '128px' | '192px' | '216px' | '224px' | '256px' | '386px';

export type RadiusToken = '4px' | '10px' | '14px' | '40px' | '64px' | '80px' | '100px' | '992px' | '1000px';

export type DurationToken = '100ms' | '200ms' | '300ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
